// flow-typed signature: add4138bff8a3916fdfe5d5cc4a8f306
// flow-typed version: <<STUB>>/@types/nodemailer_v^4.6.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/nodemailer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/nodemailer' {
  declare module .exports: any
;
}
