// flow-typed signature: 70e634af96be56ede7d676ecb80cfcb6
// flow-typed version: <<STUB>>/es6-template-string-loader_v^2.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-template-string-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-template-string-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'es6-template-string-loader/index' {
  declare module.exports: $Exports<'es6-template-string-loader'>;
}
declare module 'es6-template-string-loader/index.js' {
  declare module.exports: $Exports<'es6-template-string-loader'>;
}
