// flow-typed signature: a4d3665598388bb346fb2b124acce3c4
// flow-typed version: <<STUB>>/express-validator_v^5.2.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-validator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-validator' {
  declare module .exports: any
;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-validator/check/check' {
  declare module .exports: any
;
}

declare module 'express-validator/check/index' {
  declare module .exports: any
;
}

declare module 'express-validator/check/one-of' {
  declare module .exports: any
;
}

declare module 'express-validator/check/runner' {
  declare module .exports: any
;
}

declare module 'express-validator/check/schema' {
  declare module .exports: any
;
}

declare module 'express-validator/check/validation-chain-builders' {
  declare module .exports: any
;
}

declare module 'express-validator/check/validation-result' {
  declare module .exports: any
;
}

declare module 'express-validator/filter/index' {
  declare module .exports: any
;
}

declare module 'express-validator/filter/matched-data' {
  declare module .exports: any
;
}

declare module 'express-validator/filter/sanitization-chain-builders' {
  declare module .exports: any
;
}

declare module 'express-validator/filter/sanitize' {
  declare module .exports: any
;
}

declare module 'express-validator/lib/chain-creator' {
  declare module .exports: any
;
}

declare module 'express-validator/lib/custom-methods' {
  declare module .exports: any
;
}

declare module 'express-validator/lib/express_validator' {
  declare module .exports: any
;
}

declare module 'express-validator/lib/legacy-runner' {
  declare module .exports: any
;
}

declare module 'express-validator/lib/utils' {
  declare module .exports: any
;
}

declare module 'express-validator/tst' {
  declare module .exports: any
;
}

declare module 'express-validator/utils/constants' {
  declare module .exports: any
;
}

declare module 'express-validator/utils/filters' {
  declare module .exports: any
;
}

declare module 'express-validator/utils/format-param-output' {
  declare module .exports: any
;
}

declare module 'express-validator/utils/persist-values' {
  declare module .exports: any
;
}

declare module 'express-validator/utils/select-fields' {
  declare module .exports: any
;
}

declare module 'express-validator/utils/to-string' {
  declare module .exports: any
;
}

// Filename aliases
declare module 'express-validator/check/check.js' {
  declare module .exports: $Exports<'express-validator/check/check'>
;
}
declare module 'express-validator/check/index.js' {
  declare module .exports: $Exports<'express-validator/check/index'>
;
}
declare module 'express-validator/check/one-of.js' {
  declare module .exports: $Exports<'express-validator/check/one-of'>
;
}
declare module 'express-validator/check/runner.js' {
  declare module .exports: $Exports<'express-validator/check/runner'>
;
}
declare module 'express-validator/check/schema.js' {
  declare module .exports: $Exports<'express-validator/check/schema'>
;
}
declare module 'express-validator/check/validation-chain-builders.js' {
  declare module .exports: $Exports<'express-validator/check/validation-chain-builders'>
;
}
declare module 'express-validator/check/validation-result.js' {
  declare module .exports: $Exports<'express-validator/check/validation-result'>
;
}
declare module 'express-validator/filter/index.js' {
  declare module .exports: $Exports<'express-validator/filter/index'>
;
}
declare module 'express-validator/filter/matched-data.js' {
  declare module .exports: $Exports<'express-validator/filter/matched-data'>
;
}
declare module 'express-validator/filter/sanitization-chain-builders.js' {
  declare module .exports: $Exports<'express-validator/filter/sanitization-chain-builders'>
;
}
declare module 'express-validator/filter/sanitize.js' {
  declare module .exports: $Exports<'express-validator/filter/sanitize'>
;
}
declare module 'express-validator/index' {
  declare module .exports: $Exports<'express-validator'>
;
}
declare module 'express-validator/index.js' {
  declare module .exports: $Exports<'express-validator'>
;
}
declare module 'express-validator/lib/chain-creator.js' {
  declare module .exports: $Exports<'express-validator/lib/chain-creator'>
;
}
declare module 'express-validator/lib/custom-methods.js' {
  declare module .exports: $Exports<'express-validator/lib/custom-methods'>
;
}
declare module 'express-validator/lib/express_validator.js' {
  declare module .exports: $Exports<'express-validator/lib/express_validator'>
;
}
declare module 'express-validator/lib/legacy-runner.js' {
  declare module .exports: $Exports<'express-validator/lib/legacy-runner'>
;
}
declare module 'express-validator/lib/utils.js' {
  declare module .exports: $Exports<'express-validator/lib/utils'>
;
}
declare module 'express-validator/tst.js' {
  declare module .exports: $Exports<'express-validator/tst'>
;
}
declare module 'express-validator/utils/constants.js' {
  declare module .exports: $Exports<'express-validator/utils/constants'>
;
}
declare module 'express-validator/utils/filters.js' {
  declare module .exports: $Exports<'express-validator/utils/filters'>
;
}
declare module 'express-validator/utils/format-param-output.js' {
  declare module .exports: $Exports<'express-validator/utils/format-param-output'>
;
}
declare module 'express-validator/utils/persist-values.js' {
  declare module .exports: $Exports<'express-validator/utils/persist-values'>
;
}
declare module 'express-validator/utils/select-fields.js' {
  declare module .exports: $Exports<'express-validator/utils/select-fields'>
;
}
declare module 'express-validator/utils/to-string.js' {
  declare module .exports: $Exports<'express-validator/utils/to-string'>
;
}
