// flow-typed signature: 0dfe5e14b389de41a752a5d9254d0b56
// flow-typed version: <<STUB>>/http-status-codes_v^1.3.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-status-codes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-status-codes' {
  declare module .exports: any
;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'http-status-codes/index' {
  declare module .exports: $Exports<'http-status-codes'>
;
}
declare module 'http-status-codes/index.js' {
  declare module .exports: $Exports<'http-status-codes'>
;
}
