// flow-typed signature: a90a7edcf4c45a3648a3dc421fa73302
// flow-typed version: <<STUB>>/http-status-codes_v1.3.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-status-codes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-status-codes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'http-status-codes/index' {
  declare module.exports: $Exports<'http-status-codes'>;
}
declare module 'http-status-codes/index.js' {
  declare module.exports: $Exports<'http-status-codes'>;
}
